"""init_schema

Revision ID: e899fcda654c
Revises: 
Create Date: 2026-03-07 13:47:50.668150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e899fcda654c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nguoi_dung',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=50), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=255), nullable=False),
    sa.Column('ho_ten', sa.String(length=150), nullable=False),
    sa.Column('vai_tro', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=True),
    sa.Column('linh_vuc', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_nguoi_dung_ten_dang_nhap'), 'nguoi_dung', ['ten_dang_nhap'], unique=True)
    op.create_table('thu_tuc_hanh_chinh',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ma_thu_tuc', sa.String(length=30), nullable=False),
    sa.Column('ten', sa.Text(), nullable=False),
    sa.Column('linh_vuc', sa.String(length=50), nullable=False),
    sa.Column('ma_linh_vuc', sa.String(length=5), nullable=False),
    sa.Column('thoi_han_ngay', sa.Integer(), nullable=False),
    sa.Column('phi_xu_ly', sa.Integer(), nullable=False),
    sa.Column('yeu_cau_giay_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('can_cu_phap_ly', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('mau_van_ban', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cap_nhat_luc', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_thu_tuc')
    )
    op.create_index(op.f('ix_thu_tuc_hanh_chinh_linh_vuc'), 'thu_tuc_hanh_chinh', ['linh_vuc'], unique=False)
    op.create_table('ho_so',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ma_ho_so', sa.String(length=30), nullable=False),
    sa.Column('thu_tuc_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('can_bo_thu_ly_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cong_dan_ho_ten', sa.String(length=150), nullable=False),
    sa.Column('cong_dan_cccd', sa.String(length=20), nullable=False),
    sa.Column('cong_dan_ngay_sinh', sa.Date(), nullable=True),
    sa.Column('cong_dan_sdt', sa.String(length=15), nullable=True),
    sa.Column('cong_dan_email', sa.String(length=150), nullable=True),
    sa.Column('cong_dan_dia_chi', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.String(length=30), nullable=False),
    sa.Column('nguon_tiep_nhan', sa.String(length=20), nullable=False),
    sa.Column('lgsp_ma_ho_so', sa.String(length=50), nullable=True),
    sa.Column('ngay_tiep_nhan', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('han_giai_quyet', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ngay_hoan_thanh', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_phan_loai', sa.String(length=30), nullable=True),
    sa.Column('ai_kiem_duyet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_van_ban_path', sa.String(length=500), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ghi_chu_noi_bo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['can_bo_thu_ly_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['thu_tuc_id'], ['thu_tuc_hanh_chinh.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgsp_ma_ho_so')
    )
    op.create_index(op.f('ix_ho_so_can_bo_thu_ly_id'), 'ho_so', ['can_bo_thu_ly_id'], unique=False)
    op.create_index(op.f('ix_ho_so_ma_ho_so'), 'ho_so', ['ma_ho_so'], unique=True)
    op.create_index(op.f('ix_ho_so_trang_thai'), 'ho_so', ['trang_thai'], unique=False)
    op.create_table('nhat_ky_he_thong',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nguoi_dung_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('hanh_dong', sa.String(length=100), nullable=False),
    sa.Column('doi_tuong', sa.String(length=50), nullable=True),
    sa.Column('doi_tuong_id', sa.String(length=50), nullable=True),
    sa.Column('du_lieu_cu', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('du_lieu_moi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nhat_ky_he_thong_created_at'), 'nhat_ky_he_thong', ['created_at'], unique=False)
    op.create_index(op.f('ix_nhat_ky_he_thong_hanh_dong'), 'nhat_ky_he_thong', ['hanh_dong'], unique=False)
    op.create_index(op.f('ix_nhat_ky_he_thong_nguoi_dung_id'), 'nhat_ky_he_thong', ['nguoi_dung_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nhat_ky_he_thong_nguoi_dung_id'), table_name='nhat_ky_he_thong')
    op.drop_index(op.f('ix_nhat_ky_he_thong_hanh_dong'), table_name='nhat_ky_he_thong')
    op.drop_index(op.f('ix_nhat_ky_he_thong_created_at'), table_name='nhat_ky_he_thong')
    op.drop_table('nhat_ky_he_thong')
    op.drop_index(op.f('ix_ho_so_trang_thai'), table_name='ho_so')
    op.drop_index(op.f('ix_ho_so_ma_ho_so'), table_name='ho_so')
    op.drop_index(op.f('ix_ho_so_can_bo_thu_ly_id'), table_name='ho_so')
    op.drop_table('ho_so')
    op.drop_index(op.f('ix_thu_tuc_hanh_chinh_linh_vuc'), table_name='thu_tuc_hanh_chinh')
    op.drop_table('thu_tuc_hanh_chinh')
    op.drop_index(op.f('ix_nguoi_dung_ten_dang_nhap'), table_name='nguoi_dung')
    op.drop_table('nguoi_dung')
    # ### end Alembic commands ###
