"""add mau_van_ban

Revision ID: ee6bf6dc5a65
Revises: 6a23a5807d11
Create Date: 2026-03-07 22:20:25.731122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee6bf6dc5a65'
down_revision: Union[str, Sequence[str], None] = '6a23a5807d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mau_van_ban',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ma_mau', sa.String(length=30), nullable=False),
    sa.Column('ten_mau', sa.String(length=200), nullable=False),
    sa.Column('loai_van_ban', sa.String(length=50), nullable=False),
    sa.Column('linh_vuc', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('huong_dan', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mau_van_ban_ma_mau'), 'mau_van_ban', ['ma_mau'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mau_van_ban_ma_mau'), table_name='mau_van_ban')
    op.drop_table('mau_van_ban')
    # ### end Alembic commands ###
